"use server";

import type { TStockRow } from "./stock-adder";
import { getColor } from "@/services/color";
import { getSize } from "@/services/size";
import { createStock, createStockHistory } from "@/services/stock";
import { logger } from "@/lib/winston";
import { revalidatePath } from "next/cache";
import db from "@/db/database";
import type { Branches } from "@/types/shared";

async function ensureAutoGeneratedStockColumns() {
  const [
    stocksHasProductDate,
    stocksHasShelfLife,
    stocksHasExpireDate,
    stocksHasSupplierName,
    historyHasProductDate,
    historyHasShelfLife,
    historyHasExpireDate,
    historyHasSupplierName,
    historyHasPaidAmount,
    historyHasDueAmount,
  ] = await Promise.all([
    db.schema.hasColumn("stocks", "product_date"),
    db.schema.hasColumn("stocks", "shelf_life"),
    db.schema.hasColumn("stocks", "expire_date"),
    db.schema.hasColumn("stocks", "supplier_name"),
    db.schema.hasColumn("stock_histories", "product_date"),
    db.schema.hasColumn("stock_histories", "shelf_life"),
    db.schema.hasColumn("stock_histories", "expire_date"),
    db.schema.hasColumn("stock_histories", "supplier_name"),
    db.schema.hasColumn("stock_histories", "paid_amount"),
    db.schema.hasColumn("stock_histories", "due_amount"),
  ]);

  if (
    !stocksHasProductDate ||
    !stocksHasShelfLife ||
    !stocksHasExpireDate ||
    !stocksHasSupplierName
  ) {
    await db.schema.alterTable("stocks", function (table) {
      if (!stocksHasProductDate) table.date("product_date").nullable();
      if (!stocksHasShelfLife) table.integer("shelf_life").nullable();
      if (!stocksHasExpireDate) table.date("expire_date").nullable();
      if (!stocksHasSupplierName) table.string("supplier_name").nullable();
    });
  }

  if (
    !historyHasProductDate ||
    !historyHasShelfLife ||
    !historyHasExpireDate ||
    !historyHasSupplierName ||
    !historyHasPaidAmount ||
    !historyHasDueAmount
  ) {
    await db.schema.alterTable("stock_histories", function (table) {
      if (!historyHasProductDate) table.date("product_date").nullable();
      if (!historyHasShelfLife) table.integer("shelf_life").nullable();
      if (!historyHasExpireDate) table.date("expire_date").nullable();
      if (!historyHasSupplierName) table.string("supplier_name").nullable();
      if (!historyHasPaidAmount) table.float("paid_amount").nullable();
      if (!historyHasDueAmount) table.float("due_amount").nullable();
    });
  }
}

export async function addStockFormAction(
  productId: number,
  stockRow: TStockRow,
  branch: Branches
) {
  // console.log(productId, "prodct id from action.......");
  // console.log(stockRow, "stock row from action=======");
  // console.log(branch, "branch frm action>>>>>>>>>>>>");

  const color = stockRow.colorId
    ? await getColor({ where: { id: Number(stockRow.colorId) } })
    : null;
  const size = stockRow.sizeId
    ? await getSize({ where: { id: Number(stockRow.sizeId) } })
    : null;

  await ensureAutoGeneratedStockColumns();

  await db.transaction(async (trx) => {
    // for (let i = 0; i < parseInt(stockRow.quantity); i++) {
    //   await createStock(
    //     {
    //       product_id: BigInt(productId),
    //       branch_id: Number(branch.id),
    //       barcode: stockRow.barcode,
    //       color_id: color?.id,
    //       size_id: size?.id || null,
    //       cost: parseFloat(stockRow.costPerItem),
    //     },
    //     trx
    //   );
    //   console.log(i, "i from stock adder loop");
    // }
    await createStock(
      {
        product_id: Number(productId),
        branch_id: Number(branch.id),
        barcode: stockRow.barcode,
        color_id: color?.id,
        size_id: size?.id || null,
        cost: parseFloat(stockRow.costPerItem),
        quantity: parseInt(stockRow.quantity),
        product_date: stockRow.productDate || null,
        shelf_life: stockRow.shelfLife ? Number(stockRow.shelfLife) : null,
        expire_date: stockRow.expireDate || null,
        supplier_name: stockRow.supplierName || null,
      },
      trx
    );

    await createStockHistory(
      {
        product_id: BigInt(productId),
        barcode: stockRow.barcode,
        variant: (color?.name || "") + " - " + (size?.name || ""),
        quantity: parseInt(stockRow.quantity),
        cost_per_item: parseFloat(stockRow.costPerItem),
        paid_amount: Number(stockRow.paidAmount || 0),
        due_amount: Number(stockRow.dueAmount || 0),
        product_date: stockRow.productDate || null,
        shelf_life: stockRow.shelfLife ? Number(stockRow.shelfLife) : null,
        expire_date: stockRow.expireDate || null,
        supplier_name: stockRow.supplierName || null,
      },
      trx
    );
  });

  logger.info(
    `Stock of qty: ${stockRow.quantity} added successfully for product: ${productId}`
  );

  revalidatePath("/dashboard");
  revalidatePath("/inventories/add-stock");
  revalidatePath("/inventories/stock-list");
  revalidatePath("/inventories/stock-history");
}
