import { ContentLayout } from "@/components/admin-panel/content-layout";
import { StockAddAutoGeneratedContainer } from "./stock-adder";
import { Navbar } from "@/components/admin-panel/navbar";
import { getSuppliers } from "@/services/supplier";

export default async function AddStockAutoGeneratedPage() {
  const suppliers = await getSuppliers();

  return (
    <>
      <Navbar title="Add Stock" />
      <StockAddAutoGeneratedContainer suppliers={suppliers} />
    </>
  );
}
