"use client";

import React, { FormEvent, useEffect, useState } from "react";
import { addDays, differenceInCalendarDays, format } from "date-fns";
import { getProducts, getSelectedProduct } from "@/services/product";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { fileUrlGenerator, makeProductCode } from "@/utils/helpers";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { SendHorizontal, X } from "lucide-react";
import { addStockFormAction } from "./action";
import { useToast } from "@/components/ui/use-toast";
import type { ProductList } from "../products/columns";
import type { Colors, Sizes, Supplier } from "@/types/shared";
import { getProductColors } from "@/services/color";
import { getProductSizes } from "@/services/size";
import { useBranch } from "@/hooks/store/use-branch";
import { useStore } from "zustand";
import { Card } from "@/components/ui/card";
import { ProductSelector } from "../add-stock/product-selector";
import { createBarcode } from "@/utils/barcode";

export type TStockRow = {
  barcode: string;
  colorId: string;
  sizeId: string;
  quantity: string;
  costPerItem: string;
  paidAmount: string;
  dueAmount: string;
  productDate: string;
  shelfLife: string;
  expireDate: string;
  supplierName: string;
};

const initalStockRow: TStockRow = {
  barcode: "",
  colorId: "",
  sizeId: "",
  quantity: "",
  costPerItem: "",
  paidAmount: "",
  dueAmount: "",
  productDate: "",
  shelfLife: "",
  expireDate: "",
  supplierName: "",
};

const getExpireDate = (productDate: string, shelfLife: string) => {
  if (!productDate || !shelfLife) return "";

  const shelfLifeDays = Number(shelfLife);

  if (Number.isNaN(shelfLifeDays) || shelfLifeDays < 0) return "";

  return format(addDays(new Date(productDate), shelfLifeDays), "yyyy-MM-dd");
};

const getShelfLife = (productDate: string, expireDate: string) => {
  if (!productDate || !expireDate) return "";

  const shelfLifeDays = differenceInCalendarDays(
    new Date(expireDate),
    new Date(productDate),
  );

  if (Number.isNaN(shelfLifeDays) || shelfLifeDays < 0) return "";

  return String(shelfLifeDays);
};

const getStockTotalCost = (row: TStockRow) =>
  Number(row.quantity || 0) * Number(row.costPerItem || 0);

interface Props {
  suppliers: Supplier[];
}

export const StockAddAutoGeneratedContainer: React.FC<Props> = ({
  suppliers,
}) => {
  const { toast } = useToast();
  const branch = useStore(useBranch, (state) => state.branch);
  const [loading, setLoading] = useState<boolean>(false);
  const [selectedProduct, setSelectedProduct] = useState<string | null>(null);
  const [showDialog, setShowDialog] = useState<boolean>(false);
  const [stockRow, setStockRow] = useState<TStockRow>(initalStockRow);
  const [stocks, setStocks] = useState<TStockRow[]>([]);

  const [product, setProduct] = useState<ProductList | null>();
  const [colors, setColors] = useState<Colors[] | null>([]);
  const [sizes, setSizes] = useState<Sizes[] | null>([]);
  const [products, setProducts] = React.useState<ProductList[]>([]);

  // console.log(product?.id, "product id from stock added.............");
  // console.log(
  //   selectedProduct,
  //   "selected product from stock added............."
  // );
  // console.log(stocks, "stocks from stock added.............");
  // console.log(stockRow, "stockrow from stock added.............");
  // console.log(product, "product from stock added.............");

  React.useEffect(() => {
    getProducts({}).then((data) => setProducts(data.products));
  }, []);

  // useEffect(() => {
  //   createBarcode().then((data) => setNewBarcode(data));
  // }, [showDialog]);

  // console.log(newBarcode, "bracode from store");

  useEffect(() => {
    if (selectedProduct) {
      getSelectedProduct({
        where: { id: Number(selectedProduct) },
      }).then((product) => {
        // @ts-ignore
        setProduct(product);
      });

      getProductColors(Number(selectedProduct)).then((color) => {
        setColors(color);
      });

      getProductSizes(Number(selectedProduct))
        .then((size) => {
          // console.log(size, "size from fetchproducts&&&&&&&&&&&&&&&&&&&&&&&&&");
          setSizes(size);
        })
        .catch((error) => {
          console.error("Error fetching sizes:", error);
        });
    }
  }, [selectedProduct]);
  // console.log(sizes, "sizes from adder+++++++++++++++++++++++");
  // console.log(colors, "colors from adder??????????????????");

  // Example usage
  // const handleBarcodeSubmit = async () => {
  //   setShowDialog(true);
  //   createBarcode(
  //     Number(product?.id),
  //     Number(stockRow.colorId),
  //     Number(stockRow.sizeId)
  //   );
  //   setStockRow({ ...stockRow, barcode: newBarcode });
  // };

  // useEffect(() => {
  //   if (newBarcode) {
  //     setStockRow((prev) => ({ ...prev, barcode: newBarcode }));
  //   }
  // }, [newBarcode]);

  const handleBarcodeSubmit = async () => {
    setShowDialog(true);
  };

  const updateStockRow = (field: keyof TStockRow, value: string) => {
    setStockRow((prev) => {
      const next = { ...prev, [field]: value };

      if (field === "productDate" || field === "shelfLife") {
        next.expireDate = getExpireDate(
          field === "productDate" ? value : next.productDate,
          field === "shelfLife" ? value : next.shelfLife,
        );
      }

      if (field === "expireDate") {
        next.shelfLife = getShelfLife(next.productDate, value);
      }

      if (field === "productDate" && next.expireDate && !next.shelfLife) {
        next.shelfLife = getShelfLife(value, next.expireDate);
      }

      if (field === "productDate" && next.shelfLife) {
        next.expireDate = getExpireDate(value, next.shelfLife);
      }

      if (field === "quantity" || field === "costPerItem" || field === "paidAmount") {
        const totalCost =
          Number(field === "quantity" ? value : next.quantity || 0) *
          Number(field === "costPerItem" ? value : next.costPerItem || 0);
        const paidAmount = Number(
          field === "paidAmount" ? value : next.paidAmount || 0
        );

        next.dueAmount = String(Math.max(totalCost - paidAmount, 0));
      }

      return next;
    });
  };

  const handleStockRowSubmit = async (e: FormEvent) => {
    e.preventDefault();

    if (
      !stockRow.productDate ||
      (!stockRow.shelfLife.trim() && !stockRow.expireDate.trim())
    ) {
      toast({
        title: "Missing dates",
        description:
          "Please enter product date and either shelf life or expire date.",
        variant: "destructive",
      });
      return;
    }

    const resolvedExpireDate =
      stockRow.expireDate ||
      getExpireDate(stockRow.productDate, stockRow.shelfLife);
    const resolvedShelfLife =
      stockRow.shelfLife ||
      getShelfLife(stockRow.productDate, stockRow.expireDate);

    if (!resolvedExpireDate || !resolvedShelfLife) {
      toast({
        title: "Invalid dates",
        description: "Expire date must be after product date.",
        variant: "destructive",
      });
      return;
    }

    const totalCost = getStockTotalCost(stockRow);
    const paidAmount = Number(stockRow.paidAmount || 0);

    if (paidAmount > totalCost) {
      toast({
        title: "Invalid payment",
        description: "Paid amount cannot be greater than total cost.",
        variant: "destructive",
      });
      return;
    }

    // Generate the barcode first
    const barcode = await createBarcode(
      Number(selectedProduct),
      Number(stockRow.colorId),
      Number(stockRow.sizeId),
    );

    // Now update stockRow with the barcode
    const updatedStockRow = {
      ...stockRow,
      barcode,
      paidAmount: String(paidAmount),
      dueAmount: String(Math.max(totalCost - paidAmount, 0)),
      shelfLife: resolvedShelfLife,
      expireDate: resolvedExpireDate,
    };

    // Add the updated stock row to stocks
    setStocks([...stocks, updatedStockRow]);
    setStockRow(initalStockRow);
    setShowDialog(false);
  };

  const handleAddStockSubmit = async () => {
    // console.log("add stock click############");
    if (!product) return;
    setLoading(true);
    // console.log("after click ****************");
    // console.log(stocks, "stocks from stock added.............");
    try {
      for (let i = 0; i < stocks.length; i++) {
        await addStockFormAction(Number(product.id), stocks[i], branch);
      }
      setStocks([]);
      toast({
        title: "Success",
        description: "Stocks added successfully",
        variant: "default",
      });
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="m-6 p-4 rounded-lg">
      <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="col-span-2 flex flex-col gap-2">
          <span className="text-sm font-bold">Search Product</span>
          <ProductSelector
            products={products}
            selectedProduct={selectedProduct}
            setSelectProduct={setSelectedProduct}
          />
        </div>
        {product && (
          <>
            <div className="py-6 col-start-1 col-span-4 flex justify-between items-center gap-2 border-y-2 my-2">
              <Button onClick={handleBarcodeSubmit}>Add Stock</Button>
            </div>
            <div className="col-span-3">
              <div className="flex flex-col w-full gap-2">
                <Table className="rounded-lg overflow-hidden">
                  <TableHeader className="bg-primary">
                    <TableRow>
                      <TableHead className="text-white h-8">Code</TableHead>
                      <TableHead className="text-white h-8">Name</TableHead>
                      <TableHead className="text-white h-8">SKU</TableHead>
                      <TableHead className="text-white h-8">Category</TableHead>
                      <TableHead className="text-white h-8">
                        Selling Price
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="px-4 py-2">
                        {makeProductCode(product.id)}
                      </TableCell>
                      <TableCell className="px-4 py-2">
                        {product.name}
                      </TableCell>
                      <TableCell className="px-4 py-2">{product.sku}</TableCell>
                      <TableCell className="px-4 py-2">
                        {product.categoryName}
                      </TableCell>
                      <TableCell className="px-4 py-2">
                        {product.selling_price}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

                <Table className="rounded-lg overflow-hidden mt-2">
                  <TableHeader className="bg-primary">
                    <TableRow>
                      <TableHead className="text-white h-8">Barcode</TableHead>
                      <TableHead className="text-white h-8">Color</TableHead>
                      <TableHead className="text-white h-8">
                        Level / Size
                      </TableHead>
                      <TableHead className="text-white h-8">Qty</TableHead>
                      <TableHead className="text-white h-8">
                        Cost Per Item
                      </TableHead>
                      <TableHead className="text-white h-8">
                        Product Date
                      </TableHead>
                      <TableHead className="text-white h-8">
                        Shelf Life
                      </TableHead>
                      <TableHead className="text-white h-8">
                        Expire Date
                      </TableHead>
                      <TableHead className="text-white h-8">Supplier</TableHead>
                      <TableHead className="text-white h-8">Paid</TableHead>
                      <TableHead className="text-white h-8">Due</TableHead>
                      <TableHead className="text-white h-8">
                        Total Cost
                      </TableHead>
                      <TableHead className="text-white h-8 text-right">
                        Action
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {stocks.map((stock, index) => (
                      <TableRow key={index}>
                        <TableCell className="px-4 py-2">
                          {stock.barcode}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {
                            colors?.find((c) => String(c.id) === stock.colorId)
                              ?.name
                          }
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {
                            sizes?.find((s) => String(s.id) === stock.sizeId)
                              ?.name
                          }
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.quantity}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.costPerItem}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.productDate}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.shelfLife} days
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.expireDate}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.supplierName || "-"}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.paidAmount || 0}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {stock.dueAmount || 0}
                        </TableCell>
                        <TableCell className="px-4 py-2">
                          {getStockTotalCost(stock)}
                        </TableCell>
                        <TableCell className="px-4 py-2 text-right">
                          <Button
                            onClick={() => {
                              setStocks(stocks.filter((_, i) => i !== index));
                            }}
                            size="icon"
                            variant="ghost"
                          >
                            <X />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                  <TableFooter>
                    <TableRow>
                      <TableCell colSpan={12} className="px-4 py-2 font-bold">
                        Qty:{" "}
                        {stocks.reduce(
                          (acc, stock) => acc + parseInt(stock.quantity),
                          0,
                        )}{" "}
                        | Paid:{" "}
                        {stocks.reduce(
                          (acc, stock) => acc + Number(stock.paidAmount || 0),
                          0,
                        )}{" "}
                        | Due:{" "}
                        {stocks.reduce(
                          (acc, stock) => acc + Number(stock.dueAmount || 0),
                          0,
                        )}{" "}
                        | Total Cost:{" "}
                        {stocks.reduce(
                          (acc, stock) => acc + getStockTotalCost(stock),
                          0,
                        )}
                      </TableCell>
                      <TableCell className="text-right px-4 py-2">
                        <Button
                          onClick={handleAddStockSubmit}
                          size="sm"
                          disabled={stocks.length === 0}
                          loading={loading}
                        >
                          Add To Inventory
                        </Button>
                      </TableCell>
                    </TableRow>
                  </TableFooter>
                </Table>
              </div>
            </div>
            {product.imageUrl ? (
              <Image
                src={fileUrlGenerator(product.imageUrl)}
                className="rounded-xl"
                alt={product.name}
                height={512}
                width={512}
              />
            ) : (
              <p>No Image</p>
            )}
          </>
        )}
      </div>

      <Dialog onOpenChange={setShowDialog} open={showDialog}>
        <DialogContent className="max-w-[95vw] sm:max-w-[95vw] md:max-w-[95vw]">
          <DialogHeader>
            <DialogTitle>Enter Stock Values</DialogTitle>
          </DialogHeader>
          <form
            onSubmit={handleStockRowSubmit}
            className="grid grid-cols-1 items-end gap-5 sm:grid-cols-2 lg:grid-cols-4 "
          >
            <div className="flex flex-col gap-2">
              <Label>Color</Label>
              <Select
                onValueChange={(v) => updateStockRow("colorId", v)}
                value={stockRow.colorId}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select Color" />
                </SelectTrigger>
                <SelectContent>
                  {colors?.map((color) => (
                    <SelectItem key={color.id} value={String(color.id)}>
                      {color.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-2">
              <Label>Level / Size</Label>
              <Select
                onValueChange={(v) => updateStockRow("sizeId", v)}
                value={stockRow.sizeId}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select Level / Size" />
                </SelectTrigger>
                <SelectContent>
                  {sizes?.map((size) => (
                    <SelectItem key={size.id} value={String(size.id)}>
                      {size.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-2">
              <Label>Quantity</Label>
              <Input
                value={stockRow.quantity}
                type="number"
                min="1"
                required
                onChange={(e) => updateStockRow("quantity", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label>Cost Per Item</Label>
              <Input
                value={stockRow.costPerItem}
                type="number"
                required
                className="[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                onChange={(e) => updateStockRow("costPerItem", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label>Production Date</Label>
              <Input
                value={stockRow.productDate}
                type="date"
                required
                onChange={(e) => updateStockRow("productDate", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label>Shelf Life</Label>
              <Input
                value={stockRow.shelfLife}
                type="number"
                min="0"
                placeholder="Days"
                onChange={(e) => updateStockRow("shelfLife", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label>Expire Date</Label>
              <Input
                value={stockRow.expireDate}
                type="date"
                onChange={(e) => updateStockRow("expireDate", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label>Supplier</Label>
              <Input
                value={stockRow.supplierName}
                list="supplier-suggestion-list"
                placeholder="Type supplier name"
                onChange={(e) => updateStockRow("supplierName", e.target.value)}
              />
              <datalist id="supplier-suggestion-list">
                {suppliers.map((supplier) => (
                  <option key={supplier.id} value={supplier.name} />
                ))}
              </datalist>
            </div>
            <div className="flex flex-col gap-2 w-32">
              <Label>Paid</Label>
              <Input
                value={stockRow.paidAmount}
                type="number"
                min="0"
                placeholder="0"
                onChange={(e) => updateStockRow("paidAmount", e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2 w-32">
              <Label>Due</Label>
              <Input
                value={stockRow.dueAmount}
                type="number"
                min="0"
                readOnly
                placeholder="Auto"
              />
            </div>
            <Button
              type="submit"
              loading={loading}
              className="xl:justify-self-end flex flex-col gap-2"
            >
              <SendHorizontal />
            </Button>
          </form>
        </DialogContent>
      </Dialog>
    </Card>
  );
};
